#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("demo_uhf_uart.Resource", IsApplication=true)]

namespace demo_uhf_uart
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.99")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int arrayAntiQ = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int arrayBank = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int arrayInventoried = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int arrayMode = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int arrayPower = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int arraySession = 2130771973;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int beep = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030005
			public const int btExit = 2130903045;
			
			// aapt resource value: 0x7F030008
			public const int btnClear = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int btnFilter = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int btnGetFre = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int btnGetPower = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int btnGetSession = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int btnReadData = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int btnScan = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int btnSetFre = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int btnSetPower = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int btnSetSession = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int btnWriteData = 2130903058;
			
			// aapt resource value: 0x7F030006
			public const int btSet = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int btSetNo = 2130903047;
			
			// aapt resource value: 0x7F030013
			public const int checkBox1 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int edtTxtAddress_R = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int edtTxtAddress_W = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int edtTxtData_R = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int edtTxtData_W = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int edtTxtLeng_R = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int edtTxtLeng_W = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int edtTxtPassword_R = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int edtTxtPassword_W = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int etData = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int etLen = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int etPtr = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int layout4 = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int llContinuous = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int lvR2000 = 2130903073;
			
			// aapt resource value: 0x7F030000
			public const int LvTags = 2130903040;
			
			// aapt resource value: 0x7F030022
			public const int rbEPC = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int rbRESERVED = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int rbTID = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int rbUser = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int rdoBtn_continuous = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int rdoBtn_singleScan = 2130903079;
			
			// aapt resource value: 0x7F030028
			public const int spnBank_R = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int spnBank_W = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int spnInventoried = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int spnPower = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int spnSession = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int spnWorkMode = 2130903085;
			
			// aapt resource value: 0x7F030001
			public const int TvTagCount = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int TvTagLen = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int TvTagRssi = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int TvTagUii = 2130903044;
			
			// aapt resource value: 0x7F03002E
			public const int tvTotal = 2130903086;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int listtag_items = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int popwindow_filter2 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ReadData_Fragment = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int Scan_Fragment = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Set_Fragment = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int WriteData_Fragment = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F05000D
			public const int app_name = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int btnClear = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int btnFilter = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int btnGetFre = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int btnGetPower = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int btnGetSession = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int btnGetTime = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int btnReadData = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int btnScan = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int btnSetFre = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int btnSetPower = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int btnSetSession = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int btnSetTime = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int btnWriteData = 2131034138;
			
			// aapt resource value: 0x7F050000
			public const int China_Standard_840_845MHz = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int China_Standard_920_925MHz = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int China_Standard_plus = 2131034114;
			
			// aapt resource value: 0x7F05001B
			public const int chkAnti = 2131034139;
			
			// aapt resource value: 0x7F050003
			public const int ETSI_Standard = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int Fixed_Frequency_915MHz = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int Japan = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int Korea = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int Morocco = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int Peru_915_928MHz = 2131034120;
			
			// aapt resource value: 0x7F05001C
			public const int rdoBtn_continuous = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int rdoBtn_singleScan = 2131034141;
			
			// aapt resource value: 0x7F050009
			public const int Russia_860_867MHZ = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int South_Africa_915_919MHz = 2131034122;
			
			// aapt resource value: 0x7F05001E
			public const int tab_ReadData = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int tab_Scan = 2131034143;
			
			// aapt resource value: 0x7F050021
			public const int tab_set = 2131034145;
			
			// aapt resource value: 0x7F050020
			public const int tab_WriteData = 2131034144;
			
			// aapt resource value: 0x7F05000B
			public const int TAIWAN = 2131034123;
			
			// aapt resource value: 0x7F050022
			public const int tvAddress = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int tvBank = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int tvData = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int tvData2 = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int tvInventoried = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int tvLen = 2131034151;
			
			// aapt resource value: 0x7F050028
			public const int tvLeng = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int tvPassword = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int tvPower = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int tvPtr = 2131034155;
			
			// aapt resource value: 0x7F05002C
			public const int tvQValues = 2131034156;
			
			// aapt resource value: 0x7F05002D
			public const int tvSession = 2131034157;
			
			// aapt resource value: 0x7F05002E
			public const int tvTagCount = 2131034158;
			
			// aapt resource value: 0x7F05002F
			public const int tvTagLen = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int tvTagUii = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int tvTime = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int tvTotal = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int tvWait = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int tvWorkMode = 2131034164;
			
			// aapt resource value: 0x7F05000C
			public const int United_States_Standard = 2131034124;
			
			// aapt resource value: 0x7F050035
			public const int vietnam_918_923MHz = 2131034165;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
